# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

[package]
name = "sawtooth-seth-rpc"
version = "0.2.4"
authors = ["sawtooth"]

[[bin]]
name = "seth-rpc"
path = "src/main.rs"

[dependencies]
clap = "2"
dirs = "2"
futures-cpupool = "0.1"
jsonrpc-core = "12.0"
jsonrpc-http-server = "12.0"
log = "0.4"
protobuf = "2"
rust-crypto = "0.2"
sawtooth-sdk = "0.3"
serde_json = "1.0"
simple-logging = "2.0"
tiny-keccak = "1.4"
uuid = { version = "0.7", features = ["v4"] }

[build-dependencies]
cc = "1.0"
glob = "0.3"
protoc-rust = "2.0"
